export const projects = [
  {
    id: 1,
    name: "To do application",
    desc: "Application for making to do lists and managing them",
    stack: "HTML, CSS, JavaScript",
    url: "https://github.com/dan-skw/todoapp_vanillajs",
    photo: require("../projects/images/todolist.png"),
  },
  {
    id: 2,
    name: "Crowdfunding application",
    desc: "Page for bookmarking and chosin support level",
    stack: "React, Tailwindcss",
    url: "",
    photo: require("../projects/images/crowfunding.png"),
  },
  {
    id: 3,
    name: "Steam price bot",
    desc: "Discord bot for checking prices of games on steam praftlom ",
    stack: "Python, Discord.py",
    url: "https://github.com/dan-skw/steam_price_discord_bot_py",
    photo: require("../projects/images/discordbot.png"),
  },
  {
    id: 4,
    name: "Ceneoscraper page",
    desc: "Page for checking prices of items on ceneo",
    stack: "Python, Flask, Jinja2",
    url: "https://github.com/dan-skw/CeneoWebScraper2",
    photo: require("../projects/images/ceneoscraper.png"),
  },
  {
    id: 5,
    name: "Weather app",
    desc: "Application for checking weather in city",
    stack: "HTML, SCSS, JavaScript, Servless, Netlify, OpenWeatherMap",
    url: "https://github.com/dan-skw/weatherapp_vanilajs",
    photo: require("../projects/images/weatherapp.png"),
  },
  {
    id: 6,
    name: "Portfolio",
    desc: "Portfolio page",
    stack: "React, Tailwindcss",
    url: "https://github.com/dan-skw/reactportfolio",
    photo: "",
  },
];
